version: "3"
services:
  strapi:
    container_name: play-strapi
    image: docker.io/zerospeedzero/play-strapi:latest
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: play-strapiDB
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PORT: ${DATABASE_PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      HOST: ${STRAPI_HOST}
      PORT: ${STRAPI_PORT}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - strapi-config:/opt/app/src
    ports:
      - "1337:1337"
    networks:
      - play-strapi
    depends_on:
      - play-strapiDB
  play-strapiDB:
    image: postgres:14.0
    container_name: play-strapiDB
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
    ports:
      - "5432:5432"
    networks:
      - play-strapi

volumes:
    strapi-data:
    strapi-config:

networks:
  play-strapi:
    name: play-trapi
    driver: bridge